### ISSUE TITLE
It is not necessary to `podman pull` the benchmark-runner image

### ISSUE THREAD

**Issue by RobertKrawitz** [redhat-performance/benchmark-runner#132]
This references README.md.

`podman run` will pull the image if not already present.

**Comment by ebattat** [comment]
You right, so do you think we should delete Installation and post Installation from the readme or to put it under optional ?

**Comment by ebattat** [comment]
Remove it, also remove the post installation.

**Comment by ebattat** [comment]
Please let me know if there is more issues related to readme.
