### ISSUE TITLE
Related issues with pin nodes

### ISSUE THREAD

**Issue by RobertKrawitz** [redhat-performance/benchmark-runner#133]
I'm opening this as a single issue; all of this is tightly bound up together.

~~1. "Pin node" is not a standard Kubernetes/OpenShift term.  "Node selector" would be a better term, as that's what it is.~~
2. It should not be necessary to assign the benchmark operator pod to a node selector; let the scheduler take care of that.
3. It shouldn't really be necessary to assign the workload to a node selector.  For cases where it matters, it should be optional.
4. For workloads that should run on different nodes, pod anti-affinity would be a better construct and could be applied by the operator itself (I suspect it already does).

**Comment by ebattat** [comment]
1. You right, but this is the name convention that use in Benchmark-Operator tool in all the workloads, we need to discuss it with them.
2. This is already done. see in the readme PIN_NODE_BENCHMARK_OPERATOR environment variable 
3. We decided that node selector will turn on by default but we can control it through configuration file but true/false parameter, i.e.
[uperf template](https://github.com/redhat-performance/benchmark-runner/blob/main/benchmark_runner/benchmark_operator/templates/uperf/uperf_data_template.yaml#L4)
4. Lets discuss together and see what is the best way to use node selector feature. one option is to pass environment variable that called selector for enable/disable this feautre.

**Comment by RobertKrawitz** [comment]
1. If it's inherited from upstream, I withdraw this.
2. I don't think this (or any of the other PIN_NODE) options should be mandatory at all.
3. I don't understand?
4. Sure.  In general, I think that all of the PIN_NODE variables should be optional.  If there are situations where they shouldn't be, I'd like to analyze them.
5. I think that these should all be command line arguments, not environment variables, though.  These are all options for a specific instance of an application (benchmark-runner), not common settings that should apply across everything, such as search path, display, etc.  KUBEADMIN_PASSWORD and KUBECONFIG may qualify as the latter, but IMO the others don't.

**Comment by ebattat** [comment]
I have moved the nodes to be optional.

**Comment by ebattat** [comment]
Please let me know if there is more issues related nodes.
