### ISSUE TITLE
store benchmark run artifacts 

### ISSUE THREAD

**Issue by ashishkamra** [redhat-performance/benchmark-runner#270]
**Is your feature request related to a problem? Please describe.**
As part of every benchmark run, there are many artifacts generated such as system metrics captured in prometheus database, benchmark pod logs, other logs in OpenShift, etc. These logs and metrics provide holistic view of what happened on the cluster during the run. There is no support in benchmark runner currently to capture these run artifacts. 

**Describe the solution you'd like**
Here is a broad outline of a solution:
- Deploy a http server (or an object storage server like minio) on the provisioning machine. 
- Before a run begins. clean out the prometheus data on the cluster, and add annotations for the beginning/end of each run
- Create a directory/S3 bucket for every run with the run UUID as the directory/S3 bucket
- Put any artifacts for the run in the directory/S3 bucket towards the end of the run. Cleaning out Prometheus before each run and grabbing the prom db at the end of the run is certainly doable. We can also capture whatever logs we want.
- Index the url to the run directory/S3 bucket in elastic search associating it with the run UUID
- Combine the Prometheus metrics from the http server or the object store and benchmark run output metrics from elastic search in the grafana dashboard (that part I am not exactly sure)

**Describe alternatives you've considered**
No alternatives considered

**Comment by ashishkamra** [comment]
cc @ebattat @jeniferh @bbenshab @mnmehta @RobertKrawitz

**Comment by ebattat** [comment]
Done
