### ISSUE TITLE
Runner tries to upload Artifacts without knowing S3 details.

### ISSUE THREAD

**Issue by gqlo** [redhat-performance/benchmark-runner#421]
**Describe the bug**
Runner tries to upload Artifacts without knowing S3 details.
**To Reproduce**
`podman run --rm -e WORKLOAD=stressng_vm -e SYSTEM_METRICS=False -v $KUBECONFIG:/root/.kube/config --privileged quay.io/ebattat/benchmark-runner:latest `

**Comment by ebattat** [comment]
@gqlo, is this bug still exist ?

**Comment by gqlo** [comment]
> @gqlo, is this bug still exist ?

Just tested it on my alias cluster, it's fixed.
