### ISSUE TITLE
Benchmark-runner: Add ability to run Prometheus queries and extract output into json format

### ISSUE THREAD

**Issue by ebattat** [redhat-performance/benchmark-runner#451]
**Is your feature request related to a problem? Please describe.**
Yes, we want to have ability to run Prometheus queries directly through benchmark-runner

**Describe the solution you'd like**
We will have a queries file and benchmark-runner will parse it and run it one by one against Prometheus and return the result as json file and later upload it to Elastic and Display inside Grafana.

**Describe alternatives you've considered**
There is option to use 3rd party tool like [kube-burner](https://github.com/cloud-bulldozer/kube-burner) but I preferred to reduced dependency issue

**Additional context**
That will help us and other to get generic metric data like CPU, Memory per cluster/ node/ pod

**Comment by RobertKrawitz** [comment]
Example standalone code: https://github.com/RobertKrawitz/OpenShift4-tools/blob/main/prom-extract

Example metrics file: https://github.com/RobertKrawitz/OpenShift4-tools/blob/main/lib/clusterbuster/metrics-default.yaml

**Comment by ebattat** [comment]
Solved in [PR](https://github.com/redhat-performance/benchmark-runner/commit/7e7a69e8ca29eec47121c24090ed0cbee2f289c9)

**Comment by ebattat** [comment]
Solved in [PR](https://github.com/redhat-performance/benchmark-runner/pull/539)

**Comment by ebattat** [comment]
Solved in [PR](https://github.com/redhat-performance/benchmark-runner/pull/539)
