### ISSUE TITLE
Socket exception: Connection reset by peer (104)

### ISSUE THREAD

**Issue by ebattat** [redhat-performance/benchmark-runner#551]
**Describe the bug**
This Issue is due to warning we are starting to get when using podman from GitHub actions.
This error is shown after running ansible command that run more than 300 seconds. (OpenShift assisted-installer script)

Working properly till CI [02/01](https://github.com/redhat-performance/benchmark-runner/actions/runs/4021447216/jobs/6995719159)

First appeared at Installer CI [02/03](https://github.com/redhat-performance/benchmark-runner/actions/runs/3983220684/jobs/6828350542)

Tried the following Workaround:
1. **Workaround for GitHub actions till fix according to https://github.com/actions/runner/issues/1994 **
```
sudo -E XDG_RUNTIME_DIR= podman
```
result: skip the ansible script

2. Using docker - result: skip the ansible script

Summary:
This is just warning (Socket exception: Connection reset by peer (104)) , the installation succeeded 

Related PRs:
[sudo -E XDG_RUNTIME_DIR= podman](https://github.com/redhat-performance/benchmark-runner/pull/544)
[docker](https://github.com/redhat-performance/benchmark-runner/pull/545)
[podman](https://github.com/redhat-performance/benchmark-runner/pull/546)

**Comment by ebattat** [comment]
Solved by Github actions:
See latest [run](https://github.com/redhat-performance/benchmark-runner/actions/runs/4571445212/jobs/8069747319)

**Comment by ebattat** [comment]
Solved by Github actions:
See latest [run](https://github.com/redhat-performance/benchmark-runner/actions/runs/4571445212/jobs/8069747319)

**Comment by RobertKrawitz** [comment]
xref https://github.com/actions/runner/issues/1994
xref https://github.com/actions/runner-images/issues/6282
