### ISSUE TITLE
README.md miscellaneous issues

### ISSUE THREAD

**Issue by RobertKrawitz** [redhat-performance/benchmark-runner#75]
1.  Rather than HTML tags, use Markdown:
```
<h3 align="center">Benchmark-Runner </h3>
```
should be
```
# Benchmark-Rnner
```

2. Suggest using bold rather than fixed width for "mandatory" vs. "optional".  Fixed width would be appropriate for the variable names themselves.
3. It shouldn't be necessary to explicitly pull the benchmark-runner image; `podman run` will do so itself
4. Need explanation for `PIN_NODE1` and `PIN_NODE2`
5. The run line should not use the literal `/root/.kube`; find a placeholder.
6. It shouldn't be necessary to `podman rmi` the image unless you need to free up the space.  If one is going to do more benchmark runs, there's no reason to remove the image.

**Comment by ebattat** [comment]
1. I use <h3 align="center">Benchmark-Runner </h3> - 
Change to # Benchmark-Runner Hope it will look ok in readme PyPi (https://pypi.org/project/benchmark-runner/#post-installation) , if not I will revert it back
2. Change to bold the mark for "mandatory" vs. "optional"
3. Installation: Add bold mark as optional
4. Add explanations for PIN_NODE1, PIN_NODE2 and PIN_NODE_BENCHMARK_OPERATOR
5. /root/.kube - this is only example ,what the problem with it ?
6. Post Installation: Add bold mark as optional

**Comment by RobertKrawitz** [comment]
> 5. /root/.kube - this is only example ,what the problem with it ?

Because it's written as a literal, not as an example.  A better way to write it might be

-v "$KUBECONFIG:/root/.kube/config"
