### ISSUE TITLE
uperf_pod has hardcoded hostnames

### ISSUE THREAD

**Issue by RobertKrawitz** [redhat-performance/benchmark-runner#76]
benchmark_runner/benchmark_operator/benchmark_operator_workloads.py:176:

```
            self.__oc.wait_for_initialized(label='app=uperf-bench-server-perf-sm5039-5-6.perf.lab.en-0')
            self.__oc.wait_for_ready(label='app=uperf-bench-server-perf-sm5039-5-6.perf.lab.en-0')
```

**Comment by ebattat** [comment]
Hi Robert,

Thanks for finding this issue:
fixed: https://github.com/redhat-performance/benchmark-runner/blob/main/benchmark_runner/benchmark_operator/benchmark_operator_workloads.py#L284

Best regards,
Eli Battat.
